name: Vimana Security Scan
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Vimana Docker Build
      run: |
        chmod +x scripts/build
        export TERM=xterm
        ./scripts/build
    - name: Run Vimana security scan
      run: |
        vimana_framework:v0.8 guide --plugin dmt 
