name: Vimana Framework Security Scan
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Vimana Docker Build
      run: |
        chmod +x scripts/build
        export TERM=xterm
        ./scripts/build
    - name: Runs Vimana security scan
      run: |
        docker run -t vimana_framework:v0.8 info --plugin viewscan
        docker run -t vimana_framework:v0.8 run --plugin viewscan --project-dir "${GITHUB_WORKSPACE}"
